travis:
  secure:
    BINSTAR_TOKEN: bAgIhny19pVuouqJ3YzJio4bb9URiBc7llabrjIEtxXBaCwri1yeAr7vwxO2/4RG7hUW0TTjT6m4sMKBByEO45RHHPzVU6pMGS35XHNu20auvHib5wy2D2VFApNhDrgJRkzmH3H9KVyPI6x9fmUtV8knN27N80SvvRLwIMcoGuXhNvDYXb6Bnfr5N9tt2gCNljWDtcw09s+VRTgNzLDKe/SlU0FIvTqX/ZbUKSvkwEG5vo+x3CHJ9BvlCslZPuU+kq72mBlU2MBvoEJz+xjZAZmuNpuZNUQOa6SvUBp6zrP85vzReNUREIpQgbFmAv1YLewVW7j8vrLKR1TLxf1J6mrfMJiJw93WV784inVEo0LHHSxYhSh/EGv0zUZu8u2bDBe3ymEeDhLPUzqsIHuaVyl7hsnIkdf6Q/awlBfTqb4RraLdQhvsPcUV2bqeCDl8Boa5AfFA6QUyr7pNK88yPmMRQdGCJ4gTPJxzjciKI3YS1pRdhrGMqzZ9X7d/NDhRXmz/u6/noTZeaTScmtASxJ/YCDUrw6yqOtiD/7NWWVUaaviUmGuDH5VhUjopSbGzeT4lvkuJ7KekqmL6ruc0I5XstR0W5J7S+Ieq8y+OO4frSDjTBN7sM0E8DFI05k4+rNDEzWHYdj1DOnFNsIWWvj6U0WA/Nap+cMBHR51NLy0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
